# Generated by Django 5.2.7 on 2025-10-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='BillItem',
        ),
    ]
