# Generated by Django 5.2.7 on 2025-10-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_quantity',
            field=models.FloatField(default=0),
        ),
    ]
